# Generated by Django 5.0.6 on 2024-05-15 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_remove_ticket_comments_ticketcomment_ticket_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAssignedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='tickets', through='apiv1.TicketAssignedTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
